version: "3.7"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    sysctls:
      - net.core.somaxconn=511
  discord:
    build:
      context: ./services/discord
      target: dev
    env_file: ./services/discord/.env.dev
    volumes:
      - ./services/discord/music:/home/node/twitch-bot/music
      - ./services/discord/sounds:/home/node/twitch-bot/sounds
      - ./services/discord/src:/home/node/twitch-bot/src
    command: yarn run start:dev
    depends_on:
      - redis
