name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: install dependencies
        run: yarn install
        working-directory: services/discord
      - name: lint
        run: yarn run lint
        working-directory: services/discord
      - name: coverage
        run: yarn run coverage
        working-directory: services/discord
      - uses: codecov/codecov-action@v1
